JuliaIO/FileIO.jl

src/FileIO.jl, src/core.jl, test/runtests.jl
Following the structure from most julia packages, FileIO.jl is just the module definition with imports, exports, etc. The functionality is defined on `core.jl` that is `include`d into the module definition.
I also added some comments and changed the tests for a `.txt` file that I created. I added a test for an inexistent file.
=> Refactor and one more test

README.md, src/query.jl, test/loadsave.jl, test/query.jl
Formerly `open(file::File)` used to return an `IOStream`, now it returns a `Stream`. This seems a necessary (or at least helpful) change to support incremental read/write operations (e.g., CSVReaders.jl).
This necessitates creating wrappers for most of Base's I/O operations for `Stream`.
This also adds a number of tests (currently Coverage.jl estimates coverage as 92%).
=> Support standard I/O operations on Stream

README.md, test/loadsave.jl
As correctly pointed out in 99e64aa4875515758aac915cf8d2166fcc36892c, we were not being adequately careful about closing streams in the tests/demos.
=> Update tests, README to promote closing streams appropriately

src/FileIO.jl, test/loadsave.jl
Reverts JuliaIO/FileIO.jl#24
It seems our favorite issue,  JuliaLang/Julia#265,  strucks us here.
The unspecific load functions gets compiled into load, which then gets not recompiled for any functions that get loaded at runtime.
=> Revert "added default load method"

README.md, src/FileIO.jl, src/loadsave.jl, src/query.jl, src/registry.jl, test/loadsave.jl, test/query.jl, test/runtests.jl
and a more concise way to define default load/save library.
From Readme update:
You can also define the loaders and savers in a short form like this:
```Julia
add_format(format"OFF", "OFF", ".off", [:MeshIO])
```
This means MeshIO supports loading and saving of the `off` format.
You can add multiple loaders and specifiers like this:
```Julia
add_format(
format"BMP", 
UInt8[0x42,0x4d],
".bmp",
[:OSXNativeIO, LOAD, OSX], 
[:ImageMagick]
)
```
This means, OSXNative has first priority (gets loaded first) and only supports loading `bmp` on `OSX`.
So on windows, `OSXNativeIO` will be ignored and `ImageMagick` has first priority.
You can add any combination of `LOAD`, `SAVE`, `OSX`, `Unix`, `Windows` and `Linux`.
=> allow for multiple loader/saver libraries

README.md, src/FileIO.jl, src/loadsave.jl, test/runtests.jl, test/writemime.jl
This tries to support `writemime` in a manner similar to the file format API. In this case, the main challenge is handling the "data" argument of `writemime`, whose type may be defined in a package. Consequently, we expect the `add_mime` calls will often be made from external packages.
The main advantage this brings, over "static" implementation of `writemime`, is the ability to select different implementations based on installed packages, etc.
CC @SimonDanisch, @stevengj.
=> Add support for writemime

.travis.yml, src/FileIO.jl, src/query.jl, src/registry.jl, test/REQUIRE, test/loadsave.jl, test/query.jl
`save("myfile.ppm", img)` used to generate an error, because there are two formats (`:PPMBinary` and `:PPMText`) defined. Users will rarely care, and in almost all cases you want `:PPMBinary` anyway. So I changed the behavior from "throw an error upon creating a new file when the format is ambiguous" to "choose the first one in the list".
I also provided a new mechanism for forcing the format: `save(format"PPMBinary", "myfile.ppm", img)`. You might have thought that `save(File(format"PPMBinary", "myfile.ppm"), img)` would have been the better choice, but that runs into a problem: unless the (new) Netpbm.jl package has already been manually loaded, it falls back to the "error: no saver defined for ..." method. So we need a method with distinguishable signature, and this seemed to be the …
=> Choose a default for ambiguous formats

src/query.jl, test/query.jl
On Linux I was seeing QuartzImageIO rebuild and it turns out to have been because of
```jl
@unix_only applies_to_os{U <: Unix}(os::Type{U}) = true
```
Consequently, we don't have to rule-in our platform, but we do have to rule-out other Unices.
=> Fix OS detection

.travis.yml, src/FileIO.jl
When throwing these errors in library code, FileIO will
emit an info message and then try the next registered loader / writer.
Simon pointed me in the right direction for this.
Worth a naming check, and perhaps some tests before merging?
=> RFC: Add LoaderError and WriterError exceptions

src/error_handling.jl, src/loadsave.jl
Before this change, it was unclear exactly where to file Github issues.  This expands the error message to include the library with the error along with the instructions.
=> Report the library that triggered the error

src/registry.jl
As suggested [here](https://github.com/JuliaIO/QuartzImageIO.jl/issues/15), a pull request. Unable to do any tests, since I don't know enough Julia to understand the test suite here. :)
(I followed the instructions [here](http://docs.julialang.org/en/release-0.4/manual/packages/#making-changes-to-an-existing-package). First time for everything. Seems to work!)
=> load and save now supported on OS X

src/FileIO.jl, src/loadsave.jl, test/loadsave.jl
Before:
```jl
julia> load("nonexistent.oops")
ERROR: FileIO.File{FileIO.DataFormat{:UNKNOWN}}("nonexistent.oops") couldn't be recognized by FileIO.
in load at /home/tim/.julia/v0.4/FileIO/src/loadsave.jl:71
in load at /home/tim/.julia/v0.4/FileIO/src/loadsave.jl:42
```
Now:
```jl
julia> load("nonexistent.oops")
ERROR: SystemError: opening file nonexistent.oops: No such file or directory
in open at ./iostream.jl:90
in load at /home/tim/.julia/v0.4/FileIO/src/loadsave.jl:72
in load at /home/tim/.julia/v0.4/FileIO/src/loadsave.jl:42
```
CC @alexmulo.
=> Clarify load errors

src/registry.jl
It turns out `FLAC.jl`'s `.wav` handling is worse than I thought, so I've switched this over to `WAV.jl`, what a surprise.
=> Use `WAV.jl` for `.wav` files

src/error_handling.jl, src/loadsave.jl, test/error_handling.jl
On master, the following leads to a stack overflow:
```jl
julia> using FileIO
julia> module BrokenIO
using FileIO
end
BrokenIO
julia> add_format(format"BROKEN", (), ".brok", [:BrokenIO])
FileIO.DataFormat{:BROKEN}
julia> load(Stream(format"BROKEN", STDIN))
```
This arises because `FileIO` exports `load`, and since `BrokenIO` doesn't define its own internal `load`, `BrokenIO.load` just expands to `FileIO.load`. So `FileIO.load` ends up calling itself recursively. Moreover, because of the (unavoidable) type instability in `FileIO.load`, it's a very slow stack overflow to resolve, so it effectively results in a hang.
Now, one solution would be to recommend that packages do this:
```jl
import FileIO
using FileIO: File, Stream, @format_str
```
instead of `using FileIO`. But I believe it's more …
=> Fix stack overflow when load/save are missing

src/query.jl, test/loadsave.jl
If this seems desirable, perhaps don't hit the merge button just yet. This is technically breaking, so we might want to first merge other queued PRs, tag a version, merge this, and then tag a minor version bump.
=> Store the absolute path when querying or opening a Stream

src/error_handling.jl, src/loadsave.jl, src/query.jl, test/error_handling.jl, test/query.jl, test/runtests.jl
On master:
```Julia
julia> using FileIO
julia> load("test.png")# doesn't exist
WARNING: ErrorException("unable to open image 'test.png': No such file or directory @ error/blob.c/OpenBlob/2712")
in error(::ImageMagick.MagickWand) at /home/s/.julia/v0.5/ImageMagick/src/libmagickwand.jl:152
in readimage(::ImageMagick.MagickWand, ::String) at /home/s/.julia/v0.5/ImageMagick/src/libmagickwand.jl:231
in #load_#14(::Type{T}, ::String, ::Bool, ::Function, ::String) at /home/s/.julia/v0.5/ImageMagick/src/ImageMagick.jl:80
...
ERROR: unable to open image 'test.png': No such file or directory @ error/blob.c/OpenBlob/2712
in error(::ImageMagick.MagickWand) at /home/s/.julia/v0.5/ImageMagick/src/libmagickwand.jl:152
in readimage(::ImageMagick.MagickWand, ::String) at …
```
=> better error messages

src/loadsave.jl
See https://github.com/JuliaLang/METADATA.jl/pull/6619#issuecomment-251478364
This one relies on checking the module in which each method was defined. I worry this could be slow if the registry gets big and lots of modules (inadvisedly) extend load/save. On the other hand I can understand why legacy packages (EDIT: meaning, ones that existed before FileIO was around) are reluctant to stop exporting `load/save` and force their users to say `using FileIO`.
I am not sure how I feel about this, but on balance I suspect we should go this route.
CC @alyst
=> An alternative solution to the "missing method" problem

src/query.jl
Fixes package for jb/fasterstring branch. Should work for julia >= 0.4.
=> don't access String .data field

src/registry.jl
Should we really default to FileIO for empty loaders? Or should we strictly prohibit loading code in FileIO?
cc @juliohm 
fixes #105
=> forgot to add library

src/registry.jl
The magic numbers now match the magic numbers used by
ImageMagick. Some valid PCX files are still not identified
correctly. This addresses https://github.com/JuliaIO/FileIO.jl/issues/90.
=> Modified magic number testing for PCX image files.

src/loadsave.jl, test/loadsave.jl
This enables the following syntax:
````julia
something_you_want_to_save |> save("filename.ext")
````
I have *a lot* of follow up work on this in the pipeline that will enable some really cool data pipeline stuff, and it would be great if this could be merged and tagged soonish because I hope to get everything ready in time for my juliacon talk.
Once everything is in place, you'll be able to do things like this:
````julia
load("test.csv") |> @query(i, begin
@where i.age>30
@select {i.Name, i.Age}
end) |> save("test2.feather")
````
The follow up PRs will be support for CSV, Feather, Excel, SPSS, SAS and Stata files, all integrated with [IterableTables.jl](https://github.com/davidanthoff/IterableTables.jl) and [Query.jl](https://github.com/davidanthoff/Query.jl).
=> Add save method that returns function that acceps data

test/error_handling.jl, test/query.jl
This fixes some bugs that were introduced in #123.
In particular, there were a number of tests that used a ``save`` method with only a filename, and that collides with the stuff in #123. I think at the end of the day those test cases were artificial and can easily be changed like in this PR.
=> Fix some save calls in the tests

src/registry.jl
I'm about to register those four packages in METADATA.jl. There is a bit of a chicken and egg situation here: the tests in those four packages can only pass once this here is merged and tagged, but this here obviously only works if those four packages are registered.
Maybe the following would work: could this be merged onto ``master`` now, but not yet tagged? I'll then modify the CI builds for the four packages so that they run off the FileIO master branch. That should make those tests pass, then we can tag a new version of FileIO?
@SimonDanisch & @timholy again, thanks for helping me out with this!
=> Register CSV, Feather, Excel and various stats formats

.gitattributes
This fixes another test bug on Windows: if git is configured with the auto line ending setting, it will checkout the rda test file with CRLF line endings, and that breaks one of the tests. This setting makes sure that this file always has LR line endings. This bug didn't show up on appveyor because it uses a different git setting.
=> Add .gitattributes to fix line ending of rda test file

src/registry.jl
I'm still trying to find magic bytes for ``*.dta`` files.
I don't thing we should add magic bytes for the Excel files: both files use more generic file formats (OLE compound storage and zip files), so other files might get classified incorrectly as Excel files if we put magic bytes in.
This also removes the ``*.por`` file type. I couldn' get ReadStat.jl to read that kind of file, not sure what is going on there. Probably better to remove for now.
=> Add some magic bytes

src/registry.jl
For now, I am registering the extension `.jld2` to avoid ambiguity with JLD when saving, although someday, after JLD2 receives some testing, we may want to reassign the `.jld` extension to JLD2.
=> Add JLD2 to data formats

src/loadsave.jl, test/query.jl
=> Add module to `isdefined` calls

src/registry.jl, test/files/file.bedgraph, test/query.jl
Sorry @timholy, I somehow closed #155 when tidying my develop branch.
This pull request additionally converts the magic bytes to a string for the use of the `contains(::AbstractString, ::AbstractString)` method.
=> Custom function to find bedgraph magic bytes (take 2)

test/loadsave.jl
Loader and saver packages should define their own load/save functions, not
extend FileIO.load and FileIO.save. This fixes the `Dummy` module in the tests
to conform to this.
=> defines new load/save functions in Dummy module rather than extending FileIO's

README.md
Implementing the excellent suggestion made by @ssfrr in https://github.com/JuliaIO/FileIO.jl/pull/154#issuecomment-335932537. I hadn't realized that this wasn't clearly documented.
=> Clarify that load and save should not be extended

README.md, src/FileIO.jl, src/loadsave.jl, test/loadsave.jl
I figured it would be easier to discuss #77 if we had some code to look at. This PR is not close to mergeable, it's mostly to play with how this might work and get some feedback from you guys on whether you think this is a promising direction.
Here's the context (copied from the issue):
IIUC load and save are generally one-off operations, i.e. load("somefile.wav") loads the full wave file into memory.
Sometimes though, you have huge files that you might not want to load into memory all at once, or streams that have no end (like an internet radio stream). In my LibSndFile package I also export loadstream and savestream functions that instead return special stream types that you can read/write chunks of audio from.
@jongwook's MP3 package also has the same functionality, but it's not clear …
=> Implement loadstreaming/savestreaming API

src/FileIO.jl, src/loadsave.jl, test/loadsave.jl
closes https://github.com/JuliaIO/FileIO.jl/issues/173
also see https://github.com/JuliaImages/Images.jl/pull/714 and https://github.com/JuliaIO/ImageMagick.jl/pull/111
=> add metadata(), to avoid loading the whole file

README.md, src/loadsave.jl, test/loadsave.jl
This changes how FileIO looks for load and save functions in packages that implement support for a given file format. With this PR, it will first look for functions named ``fileio_load``, ``fileio_save`` etc. If it finds these, it will use them, otherwise it will fall back to the old way of looking for a ``load`` and ``save`` function in the package. So this PR should be completely backwards compatible.
The main benefit of this PR is that it allows a package for a file format to re-export the ``load`` and ``save`` function from FileIO. For example, [CSVFiles.jl](https://github.com/davidanthoff/CSVFiles.jl) will be able to export the function ``FileIO.load`` and ``FileIO.save`` with this patch. Right now it cannot do that: it needs to define a ``CSVFiles.load`` and ``CSVFiles.save`` …
=> Add support for fileio_* names

src/registry.jl
Tiny fix to allow RData.jl reading R 3.5 .RData files.
Could you please tag a new patch release so that I can update FileIO requirement for RData.jl?
=> Support RData version 3 (default for R >= 3.5)

src/registry.jl
Hi,
I would like to register the `BSON` data format for usage with `FileIO`.
The PR adding the interface to `BSON` can be found here: https://github.com/MikeInnes/BSON.jl/pull/31
=> add BSON data format

.gitignore, src/FileIO.jl, src/query.jl, src/registry_setup.jl, src/types.jl
I was having trouble finding things in the package.
In particular I was looking for the `Stream` type, and couldn't find it.
I think this is a bit of a cleaner restructuring of the files.
No features have been added or removed it is just code being moved around.
=> break up query.jl into seperate files

test/loadsave.jl
Some of these changes were made in #161 but it looks like I accidentally reverted them in #78. Possibly a bad merge.
This also adds tests for keyword arguments in `load` and `save`, making sure they get passed through to the handling package.
=> Dummy module now defines its own load/save instead of extending

src/error_handling.jl
Currently when there are multiple errors they are displayed using `println(err)`. This has caused issues for me because a `MethodError` prints out the argument values in full, which is pretty bad if it's a multi-megabyte array.
This PR updates it to use `showerror(err)` instead, which IMO is also more readable for the user.
Here's some code to generate errors:
```julia
using FileIO, LibSndFile
save("/tmp/test.wav", randn(100), 48000)
```
On `master` the output is:
```
Errors encountered while saving "/tmp/test.wav".
All errors:
ArgumentError("Package WAV not found in current path:\n- Run `import Pkg; Pkg.add(\"WAV\")` to install the WAV package.\n")
MethodError(LibSndFile.save_helper, (File{DataFormat{:WAV}}("/tmp/test.wav"), [-0.48550129584070445, 0.44586365763649427, 0.6812538532821187, …
```
=> use `showerror` instead of `println` to display errors

src/FileIO.jl, src/types.jl
Works around https://github.com/JuliaLang/julia/issues/34121
Fixes #246
=> Work around Julia 1.0.x segfault and fix doc warning

src/registry.jl
This defines a new format for saving profiling data in a robust manner. See the companion PR: https://github.com/timholy/FlameGraphs.jl/pull/12.
=> Register JLPROF format for storing Julia profiling data

Project.toml, src/loadsave.jl, src/query.jl, src/types.jl, test/loadsave.jl, test/query.jl, test/runtests.jl, test/test_mimesave.jl
~Maintains the same public API (e.g., type constraints on methods remains the same),
but allows FilePaths.jl to extend the public methods to work with `AbstractPath`s.
This seemed preferable to depending directly on FilePathsBase or loosening the type constraints on all methods.~
Loosen the restriction that filenames must be strings which will allow any `AbstractPath` to also work with FileIO. This approach doesn't require an explicit dependency, but I've added it as a test dependency to help ensure that `load`, `save`, `query`, etc work with the base `AbstractPath` types.
Partially addresses #219 with support from extended methods in FilePaths.jl. Also, closes https://github.com/rofinn/FilePaths.jl/issues/34.
=> Loosen filename type constraints

src/registry.jl
In my opinion it is unlikely for JLD2 to ever become a drop-in replacement for JLD.
Definitely not with full backwards compatibility - so it makes sense for the magic bytes to differ by more than just a version number.
The changes over at JLD2 are here https://github.com/JuliaIO/JLD2.jl/pull/213
=> Add new magic bytes for JLD2

Project.toml, src/loadsave.jl, src/query.jl, test/loadsave.jl
This allows `query` to return a format based only on the extension, even if the file already exists. The use-case is for `save` which just overwrites the file; in such cases, it doesn't really make sense to use any pre-existing magic bytes.
CC @dbohdan
=> Don't check magic bytes on save (fixes #267)

src/FileIO.jl
I've seen one test failure on Julia 1.1, and it's better to be safe than sorry and not take the risk.
CC @kdw503
=> Restrict precompilation to Julia 1.4.2 and higher

.appveyor.yml, .travis.yml, src/loadsave.jl, test/loadsave.jl, test/runtests.jl
The issue at the bottom was submitted to the julia discourse https://discourse.julialang.org/t/segfault-while-loading-images-in-multiple-threads/48878
This PR locks `checked_import` to ensure that loading is sequential in threaded use cases. The cost of the lock when the module is already loaded is negligible. 
`checked_import` execution times in a png-loading loop:
```
[ Info: Precompiling ImageIO [82e4d734-157c-48bb-816b-45c225c6df19]
0.459511 seconds (7.11 k allocations: 546.457 KiB, 4.52% compilation time)
0.000005 seconds (1 allocation: 16 bytes)
0.000004 seconds (1 allocation: 16 bytes)
0.000003 seconds (1 allocation: 16 bytes)
```
This may slow down parallel loops with heterogenous file types, but even in that case we can't be sure that the IO packages they're loading are …
=> Do checked_import sequentially

src/registry.jl
Netpbm.jl has been extended to load and save all netpbm formats. The changes in this PR register Netpbm.jl to perform all load/save operations for these formats.
The default (i.e. without explicit format notation) save operations are the binary formats.
=> Replaced ImageMagick by Netpbm for load/save of Netpbm files.

src/error_handling.jl, src/loadsave.jl, src/precompile.jl
These allow more concrete inference and eliminate some weird sources of latency. Very briefly, the first commit compensates for #259 (CC @rofinn, @omus), the last implements the conclusion of discussion in #226 (CC @johnnychen94). All part of a grand scheme to reduce latency (e.g., https://github.com/JuliaGraphics/Gtk.jl/pull/551#issuecomment-752990792).
=> Better precompilability

src/registry.jl
This fileformat is somewhat standardized¹ and used in various optical
flow benchmarks²³.
The package is [currently being registered](https://github.com/JuliaRegistries/General/pull/25608).
[1] https://vision.middlebury.edu/flow/code/flow-code/README.txt
[2] https://vision.middlebury.edu/flow/
[3] http://sintel.is.tue.mpg.de/
=> add `.flo` optical flow format

src/query.jl, src/registry_setup.jl
In https://github.com/JuliaIO/FileIO.jl/pull/290 I noticed that during `load` all magic byte arrays were being tested for, before the magic bytes function.
Given we can identify if there's a magic bytes function earlier, it might make sense to test that before the exhaustive test?
I've only tested this with that ImageIO PR, where load of a small file went from `192.159 μs (414 allocations: 19.67 KiB)` to `125.654 μs (325 allocations: 16.22 KiB)`
=> Try magic bytes func first, if available

src/registry.jl
Add support for reading and writing files of the [Bundler format](https://www.cs.cornell.edu/~snavely/bundler/bundler-v0.4-manual.html) used for the results of the structure from motion pipeline
=> Add Bundle format with BundlerIO.jl

src/registry.jl, test/query.jl
IOBuffer does not necessarily have a `:name` property, if it is not present fall back to using only magic bytes.
=> Identify TIFF format in IOBuffer

Project.toml, src/FileIO.jl, test/integration.jl
User must load HTTP manually for this to be activated.
(It exploits Requires.)
Closes #219
Closes #89
=> Add support for URIs

Project.toml, src/types.jl
Suggested in
https://github.com/JuliaStats/RDatasets.jl/pull/119#discussion_r589220963
=> Add compat note re File/Stream

src/loadsave.jl
Edit: It's just a typo
___
I think exposure of the MimeWriter save functions may have inadvertently dropped off in the refactor, with the change from
https://github.com/JuliaIO/FileIO.jl/blob/71bdffe1f3933aa51e7d7c42f50b90589e52d7f4/src/loadsave.jl#L143-L144
to 
https://github.com/JuliaIO/FileIO.jl/blob/b779539b505ba5aea6634c5cb78b2d2cc6e49ac8/src/loadsave.jl#L145-L150
At least, seems to fix https://github.com/JuliaIO/FileIO.jl/issues/310 for me.
I very much defer to @timholy's judgement here though about whether this is the right way to fix it
cc. @davidanthoff
=> Fix typo in save method

test/test_mimesave.jl
This would have prevented #310 (which was fixed in #311).
CC @IanButterworth, @davidanthoff
=> Add a functional-form MimeWriter test

src/precompile.jl, src/registry.jl, test/query.jl
As of `VideoIO` v0.9.1 there are simple `VideoIO.save` and `VideoIO.load` functions, which are extended to the `fileio_save` `fileio_load` names here
https://github.com/JuliaIO/VideoIO.jl/blob/77091893d21aae80cf7bca2c8550f0b55f029b36/src/VideoIO.jl#L111-L113
This adds basic functionality to load the entire video as a framestack, or write an entire framestack to file in one go.
FFMPEG can support a lot of file/container/codec types, but I thought I'd start with the common ones.
I tried to figure out how to add .mov but the magic bytes are a bit confusing. Happy to add them if someone figures out a decent heuristic.
```julia
julia> @time vid = FileIO.load("/Users/ian/Documents/GitHub/VideoIO.jl/videos/ladybird.mp4");
4.754831 seconds (3.33 k allocations: 2.300 GiB, 6.35% gc time)
julia> …
```
=> add AVI MP4 OGG and Matroska video container support via VideoIO

src/registry.jl
MP4 files are often encoded using this format, the first 4 bytes are a
box length and should not be part of the file identity magic.
=> Extend support for ISO/IEC base media format

src/loadsave.jl, test/runtests.jl, test/threaded_loading.jl
Ref https://github.com/JuliaIO/FileIO.jl/issues/336, not sure if it completely fixes the issue.
=> move package loading behind a lock

src/query.jl, src/registry.jl, test/query.jl
Also fixes the `detect_rdata` function so that it's happy with an empty file.
fixes #338
This is considered as a bug fix, so I'll tag a new patch version when it's merged.
=> fallback to extension-based guess when querying an empty file

Project.toml, src/registry.jl, test/query.jl, test/runtests.jl
#345 is introduced by #343. It turns out that `seek` is not defined for GZip stream object `GzipDecompressor`, so here it uses a per-byte strategy to check the io length.
This is a bug fix so I'll merge quickly and tag a patch version for it.
fixes #345
cc: @jonasjonker @alyst
=> check eof before read bytes

test/query.jl
For reasons not understood, Windows fails to download the test files
under Julia 1.0. It would be great if someone debugged this, but in the
meantime it seems best to work around the failure.
=> Workaround windows failure

src/error_handling.jl, test/error_handling.jl
For some errors, the entire data set being saved can be printed to
the terminal when an error is thrown. This  reduces the output.
=> Limit output when printing errors

src/registry.jl
Requires QOI.jl to be registered and https://github.com/KristofferC/QOI.jl/pull/2 to be merged
=> add QOI.jl to read and save the qoi image format

Project.toml
=> FileIO v1.12.0

docs/registry.md, src/registry.jl
Added support for [NPZ](https://github.com/fhs/NPZ.jl/pull/50) file format.
=> Added support for .npy and .npz files.

src/registry.jl, test/query.jl
This PR adds support for loading GZiped FITS files.
Astronomical FITS files are often gziped and given an extension like `.fits.gz`. Compressed fits files can be loaded directly by FITSIO.
I did my best to untangle the file loading between plain GZiped files, GZiped RData files, and GZiped fits files. 
Everything should work exactly as before unless a filename matches the `.fits.gz` pattern.
I believe this also fixes one `#FIXME` comment in `tests/query.jl` for compressed RData.
Finally, I also add support for the AstroImages library as an alternative to FITSIO which was my original purpose 😅.
=> Add Gziped fits file support and AstroImages.jl library

src/registry.jl, test/files/file.bib, test/loadsave.jl, test/query.jl
The .bib files store bibliography data which can be used in a LaTeX document. This PR registers ".bib" files with [Bibliography.jl](https://github.com/Humans-of-Julia/Bibliography.jl), which can handle parsing / importing / exporting / processing the Bibliography data.
The FileIO interfaces have been added in https://github.com/Humans-of-Julia/Bibliography.jl/pull/47
=> Add .bib files to FileIO interface

src/registry.jl
OpenCV.jl read and write several image [formats](https://docs.opencv.org/4.x/d4/da8/group__imgcodecs.html#ga288b8b3da0892bd651fce07b3bbd3a56).
This PR covers major image formats.
=> Add support for OpenCV.jl

.github/workflows/test.yml
I wonder if we can drop testing for 1.0 and save CI time.
=> Update CI for mac aarch64, codecov 4 token

.github/workflows/Documenter.yml
Switches Documenter CI from Julia nightly to 1.10
This avoids the issue in:
https://github.com/julia-actions/GitHubActions.jl/pull/34
=> Fix Documenter CI

docs/src/registering.md
=> Fix syntax in example in documentation

Project.toml, src/registry.jl
Also:
* Moved QOI to Image formats section.
* Changed AVI and WAV detectors (`detectavi`, and `detectwav`) to also use `detect_riff`.<strike> - `detect_riff` is a bit more elaborate, as it also validates the RIFF payload size (little-endian UInt32 length of the file excluding fourcc, payload_length, and optional padding).</strike>
AVI and WAV tests still pass.
Resolves #379.
Follow-up for [ImageIO.jl#67](https://github.com/JuliaIO/ImageIO.jl/pull/67)
=> Added support for WebP

test/loadsave.jl
Julia 1.12 will no longer implicitly increment world ages within expressions. However, we will likely retain world age increments between statements of a `@testset`, so all that's needed here is to move the `load` to a separate like. More explicitly, the `collect`s could be `invokelatest`'ed instead. See https://github.com/JuliaLang/julia/pull/56509
=> Adjust to Julia 1.12 change to implicit world age increment

src/registry.jl
This registers a new file format, "Hanoi Omega Automata" (https://adl.github.io/hoaf/) and its support in the package "Buchi" (https://github.com/laurentbartholdi/Buchi.jl)
=> Added HOA format
