JuliaIO/FileIO.jl

- test/FileIO.jl
- test/REQUIRE
- test/runtests.jl
- test/test.txt
> Tests using FactCheck.jl

- src/FileIO.jl
- test/loadsave.jl
> added default load method

- appveyor.yml
- src/registry.jl
wrap innards in try-finally so seekstart is always called on the stream
cc @SimonDanisch @dreammaker
> STL detection cleanups

- src/registry.jl
See https://github.com/timholy/ImagineFormat.jl
> Register the Imagine format

- src/registry.jl
Ref https://github.com/JuliaIO/MeshIO.jl/pull/20
> add abaqus inp register

- .travis.yml
- REQUIRE
- src/FileIO.jl
- src/error_handling.jl
- src/loadsave.jl
- src/query.jl
- src/registry.jl
- test/error_handling.jl
- test/query.jl
> remove depwarns and test warnings

- src/registry.jl
Should hopefully fix #82 
@alyst, would you mind taking a look at this?
> remove newline check from Rdata

- src/registry.jl
I am proposing (and coding) an extension to the file format introduced in http://gslib.com
> Register GSLIB file format

- .travis.yml
- REQUIRE
- appveyor.yml
- src/FileIO.jl
- src/query.jl
- test/error_handling.jl
- test/query.jl
and stop extending `readbytes` which no longer exists on 0.6
> Drop Julia 0.4 support

- REQUIRE
- src/query.jl
~~**DO NOT MERGE NOW!!!!**~~
~~This requires https://github.com/JuliaLang/Compat.jl/pull/325 and a new tag. I'm using this (and other) PR's to check if the implementation is correct.~~
Ready now.
> Fix 0.6 abstract type declaration depwarn

- test/REQUIRE
- test/loadsave.jl
- test/query.jl
- test/runtests.jl
> Clean up testing

- src/registry.jl
- test/loadsave.jl
Forgive me if I've missed anything.
> Adding GZIP format and tests

- src/loadsave.jl
- src/mimesave.jl
- src/registry.jl
Guess my review wasn't very thorough -.-
> fix problems with mime write

- REQUIRE
- docs/make_docs.jl
- src/query.jl
- test/loadsave.jl
- test/query.jl
> Fix most of 0.7 depwarns

- src/registry.jl
Support for [MetaImage](https://github.com/JuliaIO/MetaImageFormat.jl) files.
> Register MetaImage format

- .travis.yml
- REQUIRE
- appveyor.yml
- src/error_handling.jl
- src/query.jl
> fix depwarns under 0.7, bump REQUIRE/CI to Julia 0.6, and bump Compat version

- src/registry.jl
> prevent OMETIFF from hijacking TIFF saving

- src/registry.jl
If there is a chance that we could merge this quickly and tag a new release, it would be great. I'm trying to get a whole bunch of packages ready for a julia tutorial I'm giving next week :)
@SimonDanisch hope it is ok to ping you on this.
> Add support for Vega-Lite specifications

- .travis.yml
- REQUIRE
- appveyor.yml
- docs/make_docs.jl
- src/FileIO.jl
- src/error_handling.jl
- src/loadsave.jl
- src/mimesave.jl
- src/query.jl
- src/registry.jl
- test/error_handling.jl
- test/loadsave.jl
- test/query.jl
- test/runtests.jl
- test/test_mimesave.jl
@fredrikekre fixes for 0.7 plus one more fix!
This passes locally on windows with the newest master build of julia, so let's merge if there are no new failures!
> Fredrikekre fe/0.7

- appveyor.yml
- src/loadsave.jl
- test/error_handling.jl
- test/test_mimesave.jl
While we're waiting for implementations of a redesign (#189) here is a workaround for the current approach.
> Workaround for hot-loading handlers in Julia v0.7

- appveyor.yml
- src/query.jl
- test/query.jl
Since it no longer exists and also update AppVeyor script
> Don't try to extend Base.info

- src/error_handling.jl
Replace `warn` with `@warn`. (fixes https://github.com/JuliaIO/FileIO.jl/issues/208)
> replace warn with @warn

- .travis.yml
- appveyor.yml
Other packages are already using FileIO on 1.0, so let's advertise.
> add Julia 1.0 to CI scripts

- src/error_handling.jl
Courtesy @c42f  (thanks)
A  more indepth fix should be pursued in follow up PR's, this at least fixes the problem reported in https://github.com/JuliaIO/FileIO.jl/issues/213
> Stopgap fix of rethrow

- src/loadsave.jl
Using `Core.eval` is slow and often full of minefields. The `invokelatest` API is what's recommended for this purpose to avoid those.
> Use recommended invokelatest function instead of eval

- src/registry.jl
Needs this to be merged & tagged first: https://github.com/JuliaIO/MeshIO.jl/pull/52
> add MSH format

- src/registry.jl
> Add JLSO support

- src/registry.jl
> add support for GPX.jl

- test/error_handling.jl
- test/loadsave.jl
- test/query.jl
- test/test_mimesave.jl
Closes #271
This is basically a giant whitespace change, so presumably no need to review.
> Run everything in a test set

- Project.toml
- src/loadsave.jl
- test/integration.jl
- test/runtests.jl
Closes #288
@encendre, the `buf` here is a `Vector{UInt8}` so may demo what you're looking for.
> Add an integration test demoing streams

- src/registry.jl
> Remove GPX support (revert #299)

- docs/Project.toml
I accidentally committed the first part of this to master 6d0a3f4c809711d92e28fadd07dff46212607899, oops (thought I was on a branch).
> Add requirements for URI docs

- src/error_handling.jl
- src/loadsave.jl
- test/error_handling.jl
> Do a better job of capturing the source of errors

- Project.toml
xref https://github.com/JuliaRegistries/General/pull/31274
> Add [compat] for Requires

- test/query.jl
> Add WAV test

- Project.toml
- src/loadsave.jl
- test/files/data.csv
- test/loadsave.jl
- test/query.jl
closes #320 closes #321
cc: @davidanthoff
> relax `isfile` check to allow URL input in `checkpath_load`

- src/registry.jl
Updates the registry for LibSndFile for the following formats:
* WAV
* OGG
* FLAC
This PR is done jointly with this [PR in LibSndFile](https://github.com/JuliaAudio/LibSndFile.jl/pull/42)
> [registry] LibSndFile

- Project.toml
Here's what I have in mind of the next minor release:
Maybe:
> FileIO v1.9.0

- src/registry.jl
Fixing loading OGG files with LibSdFile
> [registry] added OGG with LibSndFile

- Project.toml
> FileIO v1.10.0

- src/registry.jl
CRef https://github.com/JuliaIO/ImageIO.jl/pull/43
> register ImageIO for sixel format

- src/registry.jl
Waiting for https://github.com/JuliaIO/ImageIO.jl/pull/45 and https://github.com/JuliaRegistries/General/pull/53821
See https://github.com/johnnychen94/JpegTurbo.jl/issues/15 for benchmark results
> registry(jpeg): add JpegTurbo and ImageIO

- docs/src/index.md
This feature has been in FileIO since 2017 and is heavily used by Queryverse, so probably it should also be documented here :)
> Document pipe style save

- src/registry.jl
> Revert "Update registry.jl"
